title: "COSINE-DP-Earth"
description: "Site de projeto para COSINE-DP-Earth"
baseurl: "/COSINE-DP-Earth"  # Caminho base do repositório GitHub Pages
url: "https://jaspior.github.io"  # URL raiz do site

# Outras configurações que você possa ter
theme: null  # Se estiver usando um tema customizado
