title: "Meu Website Personalizado"
description: "Este é o meu site personalizado"
baseurl: "" # Deixe vazio para que o site fique na raiz
url: "https://jaspior.github.io/COSINE-DP-Earth/"

# Desabilitar temas externos e usar o layout customizado
theme: null
